### ISSUE TITLE
'gengee-query -o' results in NotADirectoryError: [Errno 20]

### ISSUE THREAD

**Issue by juippis** [wimmuskee/gengee#2]
```
$ ./gengee-query -o
Traceback (most recent call last):
  File "./gengee-query", line 120, in <module>
    current_ebuilds = getCurrentEbuilds(package)
  File "/tmp/gengee/gengee/portage.py", line 32, in getCurrentEbuilds
    for package_file in listdir(getRepoPath() + "/" + package):
NotADirectoryError: [Errno 20] Not a directory: '/var/db/repos/gentoo/eclass/wxwidgets.eclass'
```
All the other options seem to work just fine.

**Comment by wimmuskee** [comment]
I got the same error, hopefully quickfixed with this: https://github.com/wimmuskee/gengee/commit/d380c2414031e13750763fd23fb5adebb6a432b8

Better fix will be to index eclasses (license/profiles) differently. Gonna work on that together with some other indexing changes.
