### ISSUE TITLE
Show all PRs assigned to maintainer

### ISSUE THREAD

**Issue by juippis** [wimmuskee/gengee#3]
Would like a way to sort all open PRs assigned to specific maintainer. Almost like what `-m` does, but expand the list. Ie, `-x gnome@gentoo.org`.

EDIT: Or simply by providing extra argument to `-m`.

**Comment by juippis** [comment]
... and perhaps similarily open them by author.

**Comment by juippis** [comment]
and sorry if I missed it, but showing all "failed to assign" PRs would be nice too :)

**Comment by wimmuskee** [comment]
When providing a value to either --author or --maintainer, the PR's for that option are shown. Also added a --label option with similar behaviour.

You have to re-update for the maintainer option.

**Comment by juippis** [comment]
Thanks :)
