### ISSUE TITLE
Show full URL to a PR

### ISSUE THREAD

**Issue by juippis** [wimmuskee/gengee#4]
This is a comfort enhancement, but would love a straight clickable link to PR in question. I know the output gets quite wide already, and this would probably require every output to be double-lined... but wanted to start discussion about it.

**Comment by wimmuskee** [comment]
Wouldn't an HTML output be better in that case?

**Comment by juippis** [comment]
Sure that's a nice option, but requires lots more work right?

**Comment by wimmuskee** [comment]
Added a -f html output option which prints html tables instead of the default ascii ones. Apparently this is a prettytable output option.
