### ISSUE TITLE
gengee-update fails with IndexError: list index out of range

### ISSUE THREAD

**Issue by juippis** [wimmuskee/gengee#9]
```
Traceback (most recent call last):
  File "./gengee-update", line 50, in <module>
    PR.setFileData(pullrequest.get_files())
  File "/home/joonas/bin/gengee/gengee/pull.py", line 70, in setFileData
    self.p["packages"].add(split_fn[0] + "/" + split_fn[1])
IndexError: list index out of range
```
It seems to die after a few ten PRs, everytime. Can't update the database.

**Comment by wimmuskee** [comment]
reproducible, and fixed with https://github.com/wimmuskee/gengee/commit/1b715efc1615e2015e0b91afa0ab02aad78e04c3

gonna do the tag later today

**Comment by wimmuskee** [comment]
added 2.2.1 tag and added ebuild for it in the flavour overlay (with py3_9)
